### ISSUE TITLE
is 8.0.7 stable ?

### ISSUE THREAD

**Issue by JSN-1** [ryansch/docker-unifi-rpi#107]
Hi

First of all thanks for maintaining unifi for rpi, it's much appreciated.

I can see you have added 8.0.7, but it not tagged as latest, so question goes is 8.0.x stable ?

Thanks in advance

**Comment by ryansch** [comment]
It does look like 8.0.7 was promoted to stable. I'll tag it as latest.

In other news, I'm working to get 8.0.24+ working as the mongo signing key has expired and we're looking at another mongo upgrade.

**Comment by JSN-1** [comment]
thanks a lot
