### ISSUE TITLE
8.0.24+ needs a new mongo

### ISSUE THREAD

**Issue by ryansch** [ryansch/docker-unifi-rpi#108]
The hack we've been using to pull in mongo 3.6.x has finally broken.

Unifi 7.5 and greater supports mongo 4.4. I'm looking at upgrading to it.

**Comment by mhzawadi** [comment]
Hello 👋🏼 

Any update on this?

**Comment by loganmarchione** [comment]
The Release Candidate for 8.1.113 just dropped. 

https://community.ui.com/releases/UniFi-Network-Application-8-1-113/af46fd38-8afe-4cef-8de1-89636b02b52c

I find this part the most interesting...

> UniFi Network Application 7.5 and newer requires MongoDB 3.6 and Java 17.
> - Version 7.5 till 8.0 supports up to MongoDB 4.4.
> - Version 8.1 and newer supports up to MongoDB 7.0.

**Comment by ryansch** [comment]
@loganmarchione Whoa.

**Comment by ryansch** [comment]
Honestly, I might just skip straight to 8.1 at this point.

**Comment by loganmarchione** [comment]
FYI if you plan to upgrade MongoDB while upgrading Unifi. Versions 5 and later require AVX512 CPU instructions, or they won't boot.

https://github.com/docker-library/mongo/issues/485
https://www.mongodb.com/docs/manual/administration/production-notes/#x86_64

**Comment by ryansch** [comment]
Your feedback is _incredibly_ helpful! This pain is part of the reason why there hasn't been a new release in a while.

**Comment by ryansch** [comment]
I'm not dead. This is still on my radar.

**Comment by mhzawadi** [comment]
If it helps in any way, I have run the GlennR install a unifi on my mac (an M1 Pro) and I can see it might have worked.

Will get it running with exposed ports and confirm its really working

**Comment by ryansch** [comment]
I just shipped 8.1 with mongo 4.4.18. Works on my pi4.
