### ISSUE TITLE
Managed to install docker+Unifi latest on Raspi 4B with 64bit bookworm.... some remarks on "Release file" error. 

### ISSUE THREAD

**Issue by doremifajb** [ryansch/docker-unifi-rpi#112]
Hello! I just burned a fresh Pi OS bookworm 64bit, in order to use Unifi Controller with your method. I managed it! Everything is working great, together with my bunch of EOL APs (old UAPs) being able to be managed by the latest Controller. Thank you very much! 

Now I wanted to mention that, with your instruction under "Now let's install docker.", I got error messages: 
```
Ign:5 https://download.docker.com/linux/ubuntu bookworm InRelease              
Err:6 https://download.docker.com/linux/ubuntu bookworm Release
  404  Not Found [IP: 18.239.94.55 443]
Reading package lists... Done
E: The repository 'https://download.docker.com/linux/ubuntu bookworm Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```
and then that `Package docker-ce is not available` and so on, the same with docker-ce-cli. I found this page: 

https://www.thomas-krenn.com/de/wiki/Docker_Installation_unter_Debian_12

It's in German, is similar to your code but a bit different, and this worked. (Just copy and paste)

In case someone else might have the same problem, I thought I would post it here....

**Comment by ryansch** [comment]
I had to update the installation instructions as they had gotten out of date. Thanks for the feedback!
