### ISSUE TITLE
Imported backup but can't sign in

### ISSUE THREAD

**Issue by DavidDeSloovere** [ryansch/docker-unifi-rpi#22]
Hello Ryan, first let me say: thanks for your work on this docker solution.

I'm coming from another setup, also on a Pi, but not in docker. I have exported my config and then imported into the new setup that runs on your docker solution.
But now I can't sign in. I'm getting the form, but my old credentials don't work. 
> Login error. Invalid username and/or password.

Also can't get a reset via email. The mail isn't sent. Maybe because smtp setting is incorrect.

Any idea on how I can fix this? I would either need to fix the smtp setting, or reset the account manually. I've found solutions to 'reset' the password in the mongo database, but I'm not sure if that's possible via docker.

I know a bit of docker, but I don't know where to find the local folders the volumes are mapped to.

**Comment by ryansch** [comment]
Did you import your config through the UI?  That's odd!

So the easiest way to get access to the "docker volumes" where the data is stored is to use docker-compose to start up a container running an interactive shell.

```sh
# From the directory where your docker-compose.yml is
docker-compose run --rm unifi bash
```

**Comment by DavidDeSloovere** [comment]
Thanks. I'll have a look.
