### ISSUE TITLE
Having issues with the image tags

### ISSUE THREAD

**Issue by maxpousre** [ryansch/docker-unifi-rpi#31]
I pulled your compose file down directly. No matter what tag I us, even leaving it alone as 'latest' I get a manifest error. 

ERROR: no matching manifest for unknown in the manifest list entries

**Comment by ryansch** [comment]
@maxpousre What version of docker are you using?  `docker version` can give that to you.

**Comment by maxpousre** [comment]
Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:49 2018
 OS/Arch:           linux/arm64
 Experimental:      false

**Comment by ryansch** [comment]
@maxpousre I see the issue.  I haven't built an arm64 image.  Adding that now.

**Comment by maxpousre** [comment]
Thanks for that @ryansch ! I appreciate the effort.
