### ISSUE TITLE
UniFi Controller is starting up... Never Starts Rock64 

### ISSUE THREAD

**Issue by Jswee1** [ryansch/docker-unifi-rpi#32]
So I’m on the Rock64 installed /ryansch/docker-unifi-rpi installs correctly it starts up on the web page but all I get is unifi controller is starting up nothing else. I used these commands to install. 
```
cd /opt 
sudo git clone https://github.com/ryansch/docker-unifi-rpi unifi 
sudo systemctl enable /opt/unifi/contrib/unifi.service 
docker pull ryansch/unifi-rpi:latest (For download and extract progress) 
sudo systemctl start unifi
```
 The Rock64 is arm64/armhf hopefully architecture isn’t why it’s not working correctly. Any help is great!

**Comment by ryansch** [comment]
What's `uname -a` say?  I don't have access to an arm64 device so this is a hard use case for me to test.

Note to watchers: If you can tell me how to get java to skip the arch check when running under qemu it would really help.

**Comment by AndreasRavn** [comment]
Same problem here apparently, uname -a output:

`Linux albula 4.4.132-1072-rockchip-ayufan-ga1d27dba5a2e #1 SMP Sat Jul 21 20:18:03 UTC 2018 aarch64 GNU/Linux`

**Comment by AndreasRavn** [comment]
> Same problem here apparently, `uname -a` output:
> 
> `Linux albula 4.4.132-1072-rockchip-ayufan-ga1d27dba5a2e #1 SMP Sat Jul 21 20:18:03 UTC 2018 aarch64 GNU/Linux`

But after update to newest version of the distro, `uname -a` says:

`Linux albula 4.4.132-1075-rockchip-ayufan-ga83beded8524 #1 SMP Thu Jul 26 08:22:22 UTC 2018 aarch64 GNU/Linux`

And your unifi image works, I think you can close this issue now

**Comment by ryansch** [comment]
Whoa.  That's an interesting result!  Thanks for the feedback @AndreasRavn.
