### ISSUE TITLE
Swarm support ?

### ISSUE THREAD

**Issue by sandys** [ryansch/docker-unifi-rpi#35]
hi guys,
would you be able to migrate from docker-compose to docker swarm ? it will allow us to layer on more tools like Portainer for management (fantastic UI, just 4mb of memory) - https://portainer.io/install.html

**Comment by ryansch** [comment]
You don't need swarm just for portainer.  Swarm is more about orchestration/scheduling across multiple docker engines/nodes.  In this case, I'd recommend creating a docker compose file that specifies portainer and a systemd unit file that starts it.  You can use the docker-compose.yml linked on https://portainer.io/install.html along with adapting the unit file here: https://github.com/ryansch/docker-unifi-rpi/blob/master/contrib/unifi.service

Let me know if you have any questions @sandys.
