### ISSUE TITLE
Don't get any response on url

### ISSUE THREAD

**Issue by thijsvanbloemendaal** [ryansch/docker-unifi-rpi#36]
Hi!

I was trying to use the container you've created. I used the instructions ons the docker hub, but after the container started the url doesn't give any response.
After the docker compose didn't work I tried to use the image directly like this:
 docker run -d --name="unifi" -v /home/pi/dockerdata/unifi/config:/var/lib/unifi -v /home/pi/dockerdata/unifi/log:/usr/lib/unifi/logs -v /home/pi/dockerdata/unifi/log2:/var/log/unifi -v /home/pi/dockerdata/unifi/run:/usr/lib/unifi/run -v /home/pi/dockerdata/unifi/run2:/run/unifi -v /home/pi/dockerdata/unifi/work:/usr/lib/unifi/work --restart unless-stopped --net=host ryansch/unifi-rpi:v5

But that is working neither.

Can you help me to get this running? I'm using a Raspian Pi 3b and i'm running more containers that are working.

Thanks in advance!

**Comment by ryansch** [comment]
@thijsvanbloemendaal The `v5` tag isn't supported.  Please try again with `5`.

**Comment by thijsvanbloemendaal** [comment]
Thank you for the quick response @ryansch !
I've tried it already with `latest` and now with `5`, but the behavior seems to stay the same.
Docker PS shows me: `Restarting (255) About a minute ago`

**Comment by ryansch** [comment]
@thijsvanbloemendaal That's strange. Do you have a valid `system.properties` file?  Does the container have write access to `/home/pi/dockerdata/unifi/config`?

**Comment by ryansch** [comment]
@thijsvanbloemendaal If I look at the data inside of my container volume I see `/var/lib/unifi/system.properties`.  What happened when you tried to use the docker-compose solution?  This bug seems somehow related to your specific environment.

**Comment by thijsvanbloemendaal** [comment]
@ryansch a few days ago my sd card became corrupt. After reinstallation of the pi the image started working! Same steps so I still don’t understand how, but it works! Thanks for your help!
