### ISSUE TITLE
[Minor Bug]Java Warnings On Creation

### ISSUE THREAD

**Issue by Richyread** [ryansch/docker-unifi-rpi#39]
Just a small bit of feedback - I'm seeing some 'Connection refused' error messages for 'java.net.Connect' and a 'Java HotSpot Client' warning, when launching the image on a fresh stretch-lite install (copy from log attached).

The container still starts and seems to run fine, but seems there's some sort of disconnect/timeout problem and/or http>https issue it's encountering during the initial configuration that needs a tweak or poke etc! :-)

Cheers,

Richy.
[Java_Warning_Log.txt](https://github.com/ryansch/docker-unifi-rpi/files/2826110/Java_Warning_Log.txt)

**Comment by ryansch** [comment]
@Richyread I've seen other people reporting this log output upstream on the unifi forums.  I'm going to count this as an upstream issue and close this.
