### ISSUE TITLE
move to openjdk-8-jdk from oracle jdk

### ISSUE THREAD

**Issue by mstoops** [ryansch/docker-unifi-rpi#40]
I and others have recently experienced issues with the oracle jdk on bare metal, and before moving over to your docker setup, I was able to easily make this switch, based on these recommendations: 

`https://www.reddit.com/r/Ubiquiti/comments/au52p8/a_few_lessons_i_learned_creating_a_raspberry_pi/?st=JSK22ZE2&sh=241980c2`

Does this make sense to do?

The second recommendation in that article is to installed the `haveged` package to help speed things up. Another addition, maybe?

**Comment by ryansch** [comment]
@mstoops It seems like the issues with the oracle jdk are related to the version pulled in with the package manager.  You'll notice I worked around that with [oracle-java8-installer](https://launchpad.net/~webupd8team/+archive/ubuntu/java).  Have you had any issues with the version of java I have in the container image?

What problem are you trying to solve with `haveged`?  Have you noticed a lack of entropy causing issues?  We're not issuing certificates or anything else that I'm aware of that would consume more entropy than the kernel is able to supply.
