### ISSUE TITLE
Cannot start after update

### ISSUE THREAD

**Issue by Nyqi** [ryansch/docker-unifi-rpi#44]
It gives me this error after update with docker-compose pull

[https://hastebin.com/ukumifehut.rb](https://hastebin.com/ukumifehut.rb)

**Comment by ryansch** [comment]
That's a new one. Can you try deleting the container image and pulling it again? Are you mounting anything into your container or setting any environment variables that would effect the JVM?

**Comment by Nyqi** [comment]
I already fixed it by removing docker image and volumes and then I did `docker-compose up -d` and it's working again.

**Comment by ryansch** [comment]
Excellent! If you're able to reproduce, please reopen this issue.
