### ISSUE TITLE
 unifi  standard_init_linux.go:207: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by ThePfaffanater** [ryansch/docker-unifi-rpi#45]
Running inside a docker container with BalenaOS on a RaspberryPi B+ it refuses to start responding with  
> unifi  standard_init_linux.go:207: exec user process caused "exec format error"

 followed by 
> Service exited 'unifi sha256:[long string]

It then restarts.
The logs contain no other information. Please direct me to anywhere I could get more detailed logs so I can figure this out.

**Comment by ryansch** [comment]
@ThePfaffanater Could you run `uname -a` and post the output here?

**Comment by ThePfaffanater** [comment]
Was able to resolve the issue

**Comment by mschadee** [comment]
@ThePfaffanater What did you do to resolve this? I have the same issue.

**Comment by mschadee** [comment]
> If it gives an exec format error, the architecture is wrong.

https://github.com/balena-os/balena-raspberrypi/issues/313#issuecomment-473849170
