### ISSUE TITLE
Is port 8081 actually used by UniFi?

### ISSUE THREAD

**Issue by loganmarchione** [ryansch/docker-unifi-rpi#46]
I see you're exposing port 8081/tcp.

However, on [this page](https://help.ubnt.com/hc/en-us/articles/218506997-UniFi-Ports-Used), port 8081 is not mentioned. In addition, [this page](https://community.ui.com/questions/Confused-Which-Ports-to-Open-on-the-Firewall/7ce35348-9b4a-42ab-90e4-d006dad2f7f2#answer/66a78306-e15c-4204-946b-42ac0bd9b55a) has someone asking a similar question, where it is said that 8081 can be closed. On my controller running on a KVM, netstat shows that 8081 is not being listened on either.

Is 8081 actually used by UniFi?

**Comment by ryansch** [comment]
It looks like 8081 used to be used for some kind of local management. I think we can go ahead and remove it.

**Comment by ryansch** [comment]
Fixed in 2149ff4318e8b32735ec7e5780ebbda7134c68da
