### ISSUE TITLE
OpenJDK Client Warnings & Java IllegalStateException Errors

### ISSUE THREAD

**Issue by Richyread** [ryansch/docker-unifi-rpi#49]
Fresh install on RPi 3B+ seeing the below in the log files (as viewed through Portainer)

![Screenshot 2019-08-28 at 16 16 21](https://user-images.githubusercontent.com/7470850/63869680-753efc80-c9b0-11e9-9b73-019644b91405.png)

Is it safe to ignore the warning or do I need to tweak the Java settings etc?

Richy.

**Comment by ryansch** [comment]
The stack guard warnings are normal for the unifi controller.
