### ISSUE TITLE
Add let's encrypt support

### ISSUE THREAD

**Issue by ryansch** [ryansch/docker-unifi-rpi#5]

**Comment by ratherd** [comment]
I'm interested in this enhancement. I was hoping to find a way to add an Let's Encrypt certificate, possibly the recently available wildcard or otherwise per host. Thanks for providing this docker image already to the community.

**Comment by sergeifilippov** [comment]
While this is feature is being thought about, is there a way to get a valid certificate into the current docker image? Maybe via folder/file mount?

This way, if you already have Lets Encrypt working via somethings like [acme.sh](https://github.com/Neilpang/acme.sh) outside the image, you can just load in an externally generated cert.

Thank you for this project 👍🏻

**Comment by ryansch** [comment]
@sergeifilippov Here's the official documentation for sideloading ssl certs: https://help.ubnt.com/hc/en-us/articles/212500127-UniFi-SSL-Certificate-Error

**Comment by ryansch** [comment]
I'm probably going to go with a setup based on running nginx and https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion/ in front of the controller container via a different docker-compose file.

**Comment by sergeifilippov** [comment]
I keep hearing good things about [traefik](https://traefik.io/) so might take it for a spin.

**Comment by ryansch** [comment]
Actually that's a pretty good idea...

**Comment by sergeifilippov** [comment]
Closed by #24 ?

**Comment by ryansch** [comment]
@sergeifilippov Almost.  Still tweaking and I need to add docs.  That's very close to what's going to be merged though.

**Comment by ryansch** [comment]
Closed via #24.

Docks linked in README: https://github.com/ryansch/docker-unifi-rpi#tls-support

**Comment by ryansch** [comment]
Ping @sergeifilippov ^
