### ISSUE TITLE
Testing/Unstable tag for docker images

### ISSUE THREAD

**Issue by haup** [ryansch/docker-unifi-rpi#53]
Hi Ryan, 

thanks so much for your great work. I am using the your docker image since a couple of years and I am also very happy about especially when it comes to updates. I am using the watchtower image to update my controller automatically and it works always like a charme. 

For convenience purposes I would like to request a new general tag for testing/unstable versions of the controller versions like you have done for the stable version with "latest" or "5" and so on. Or is that explicitly not wanted from you?

**Comment by ryansch** [comment]
I've been hesitant to add tags for anything other than stable releases as I haven't had a chance to automate pulling update information from ubiquiti and the testing/unstable tags would need to be updated much more frequently.

I'm open to the idea but it needs that automation first.
