### ISSUE TITLE
5.12.22 now stable

### ISSUE THREAD

**Issue by ablyler** [ryansch/docker-unifi-rpi#55]
5.12.22 was marked as stable on 2019-10-29: https://community.ui.com/releases/UniFi-Network-Controller-5-12-22/263c8b60-def8-4667-85c3-87a6200a6c9b#comment/57403c30-8bf5-4cb8-8aa4-f3408cb6f4cb

**Comment by ryansch** [comment]
Thanks!

With the new software releases I no longer get notifications when they're promoted to stable.
