### ISSUE TITLE
Cannot find libjvm.so

### ISSUE THREAD

**Issue by Matthijsy** [ryansch/docker-unifi-rpi#57]
I am using this docker image for some while now. However, I have restarted my pi and now the docker file won't run anymore. It crashes with the following error:

```
unifi    |     invalid section len 4194352, max remaining 48
unifi    |     ignoring unknown attr section agabi
unifi    | Error: dl failure on line 893
unifi    | Error: failed /usr/lib/jvm/java-8-openjdk-armhf/jre/lib/arm/client/libjvm.so, because /usr/lib/jvm/java-8-openjdk-armhf/jre/lib/arm/client/libjvm.so: cannot open shared object file: No such file or directory
```

I have also tried to follow the installation again (to get a fresh version) but that crashes with the same error. I am running an RPI 3B. Is this a known issue or am I doing something wrong?

**Comment by lancelon** [comment]
Also having this issue with hassio and the unifi direct add on

**Comment by ryansch** [comment]
@Matthijsy I haven't been able to reproduce this error. Are you still having this issue?

**Comment by Matthijsy** [comment]
It seems to work now, I don't remember how I fixed it but it is running correctly now

**Comment by ryansch** [comment]
Excellent!
