### ISSUE TITLE
Version 5.12.46 Beta

### ISSUE THREAD

**Issue by flobernd** [ryansch/docker-unifi-rpi#58]
Hi there,

would you mind adding support for the latest 5.12.46 Beta version? I'm usually not into beta versions, but this one contains a very important bugfix for me and I would love to test it.

I guess you are taking some days off over the hoildays anyways, but I will patiently wait.

Best regards

**Comment by ryansch** [comment]
@flobernd Done!

**Comment by flobernd** [comment]
Thanks for the X-Mas present 😆
