### ISSUE TITLE
ssl_match_hostname

### ISSUE THREAD

**Issue by lowrisk75** [ryansch/docker-unifi-rpi#59]
I'm I missing something ?
I'm on a raspberry pi 4 but can't create the container 

> pi@raspberrypi:~/unifi $ sudo docker-compose up -d
> Traceback (most recent call last):
>   File "/usr/local/bin/docker-compose", line 6, in <module>
>     from compose.cli.main import main
>   File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 18, in <module>
>     import docker
>   File "/usr/local/lib/python2.7/dist-packages/docker/__init__.py", line 2, in <module>
>     from .api import APIClient
>   File "/usr/local/lib/python2.7/dist-packages/docker/api/__init__.py", line 2, in <module>
>     from .client import APIClient
>   File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 10, in <module>
>     from .build import BuildApiMixin
>   File "/usr/local/lib/python2.7/dist-packages/docker/api/build.py", line 6, in <module>
>     from .. import auth
>   File "/usr/local/lib/python2.7/dist-packages/docker/auth.py", line 9, in <module>
>     from .utils import config
>   File "/usr/local/lib/python2.7/dist-packages/docker/utils/__init__.py", line 3, in <module>
>     from .decorators import check_resource, minimum_version, update_headers
>   File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 4, in <module>
>     from . import utils
>   File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 13, in <module>
>     from .. import tls
>   File "/usr/local/lib/python2.7/dist-packages/docker/tls.py", line 5, in <module>
>     from .transport import SSLHTTPAdapter
>   File "/usr/local/lib/python2.7/dist-packages/docker/transport/__init__.py", line 3, in <module>
>     from .ssladapter import SSLHTTPAdapter
>   File "/usr/local/lib/python2.7/dist-packages/docker/transport/ssladapter.py", line 23, in <module>
>     from backports.ssl_match_hostname import match_hostname
> ImportError: No module named ssl_match_hostname

**Comment by ryansch** [comment]
@lowrisk75 That looks like an issue with your docker-compose install.
