### ISSUE TITLE
SSL problem

### ISSUE THREAD

**Issue by mmaxbar** [ryansch/docker-unifi-rpi#63]
i have this really strange problem where the container ran fine for a couple of days now and out of sudden I got this error code from firefox when trying to connect to the unifi controller:

SSL_ERROR_RX_RECORD_TOO_LONG

After googling around a bit, i got it "solved" by setting up firefox to not use TLS 1.3 (about:config/security.tls.version.max=3) --> not a good solution

googling more i found that after disabling ipv6 on the pi i can now acess the unifi controller without modifying the tls.version.max, but only when using private mode...
I am now completely lost what the causes of the problems are but I figured it may be at least in part a container configuration topic because the container should be able to run fine on a standard raspbian buster install... maybe something wrong with the way certificates are created in the container?

Any hints welcome...

**Comment by mmaxbar** [comment]
problem disappeared, i cannot reproduce it any more...

**Comment by ryansch** [comment]
Strange!
