### ISSUE TITLE
Unable to load '/data/system.properties' after building new image and importing

### ISSUE THREAD

**Issue by kfken** [ryansch/docker-unifi-rpi#64]
I used build.sh to build v5.14.18-arm32v7 and it appears to complete successfully.  After performing "docker save ..." to export the image as a tar, transfer to my pi4 and import using "docker load ...", I get the following message when trying to run it.

Unable to load '/data/system.properties' - /usr/lib/unifi/data/system.properties
 (No such file or directory) 

I'm running using "docker run -i -t 5.14.18" (I had tagged it with this).  I'm probably missing something obvious, but wanted to see if this was a Unifi specific problem and I need to do some manual steps when upgrading.

**Comment by ryansch** [comment]
I haven't tried the `docker save`, `docker load` dance with this image but I don't know why it wouldn't work. Could you share either your compose setup or your `docker run` line?

**Comment by kfken** [comment]
Ahh yes, see I knew it was something simple I was missing.  That's my entire line, I need to assign the volumes as in your docker-compose.  Thanks.

**Comment by ryansch** [comment]
@kfken I'm glad you got it figured out!
