### ISSUE TITLE
"latest" tag not updated

### ISSUE THREAD

**Issue by naeramarth7** [ryansch/docker-unifi-rpi#65]
Contrary to the documentation, the [latest tag](https://hub.docker.com/r/ryansch/unifi-rpi/tags?page=1&name=latest) still points to [5.13.32](https://hub.docker.com/layers/ryansch/unifi-rpi/latest/images/sha256-accf7eb424eb151bf8f862e7b51925a54d1d8c1b877d2469831abb933982e8b5?context=explore). Thus, using the _latest_ tag it's not possible to update the UniFi instance to the actual latest version.

**Comment by ryansch** [comment]
@naeramarth7 Thanks for letting me know. I've fixed the tags for 5.14.23.
