### ISSUE TITLE
6.x stable

### ISSUE THREAD

**Issue by ryansch** [ryansch/docker-unifi-rpi#68]
I'm holding off on marking any 6.x release as `latest` due to the forum traffic around the release. It seems like it needs a little more time in the oven.

**Comment by ryansch** [comment]
Looks like 6.0.22 also has serious issues. Still holding off.

**Comment by ryansch** [comment]
https://community.ui.com/releases/UniFi-Network-Controller-6-0-23/6ee72622-e3ca-4ebe-9e82-97fe7cca2094

I'm monitoring.

**Comment by ryansch** [comment]
https://community.ui.com/releases/UniFi-Network-Controller-6-0-24/d897a089-4f1d-4fc5-ab5a-0d9f034f91fd?page=1

6.0.24 is looking better but there's still an issue with `VLANs beyond UAP wireless downlinks may not have connectivity`. I may still hold off because of that.

**Comment by ryansch** [comment]
https://community.ui.com/releases/UniFi-Network-Controller-6-0-26/4d5d550d-8b4b-4387-ba14-e8065872dca5

I'm intending to mark 6.0.26 as `latest` if there aren't any glaring issues.

**Comment by Vetti52** [comment]
According to [UniFi ](https://community.ui.com/releases) the current stable release is Network Controller 6.0.23. 6.0.24 as of today is RC. There is no 6.0.26 release mentioned at all. Your link above lands on UI 404. Please give me a ride in your DeLorean back to the future, or confirm, that 6.0.26 is a stable candidate and works fine! ;-)

**Comment by ryansch** [comment]
@Vetti52 Releases start on the beta side of the forum. You can login and request access. They will become publicly available when unifi promotes them to RC.

**Comment by Vetti52** [comment]
Ok, so I should look at the beta side of the world. 
Well, the topic was "6.x stable", where I thought, that there was a "stable" 6.0 version as a docker container. But, up to date, you provide no RC or stable version of 6.x (with respect to Ubiquity this should be 6.0.23), but only "latest", which currently is 6.0.26 beta. Right? In summary, actually there is no reason to upgrade to any of 6.x versions, when looking for a stable environment. As the Ubiquity community is complaining about all 6.x versions at all, you hopefully will communicate, if it somewhen will happen, that we could use 6.x in practice.

**Comment by ryansch** [comment]
@Vetti52 It's docker convention to use `latest` as the most recent stable release of a project. I only marked a 6.x release as `latest` this morning. You can see more about this approach in the project README.

**Comment by ryansch** [comment]
I've just released 6.0.27 and marked it as `latest`.

**Comment by Vetti52** [comment]
So, unfortunately Ubiquity tagged 6.0.27 as "Official". Whatever this means. The "official" version at "https://www.ui.com/download/unifi/" is still 6.0.23, which you skipped in your comments completely. So currently I know, which docker version is "latest", but I can't figure out, which version in fact is "stable", with respect to Ubiquity's releases.

**Comment by ryansch** [comment]
@Vetti52 I'm using the release information from https://community.ui.com/releases
