### ISSUE TITLE
Port 8080 not available / kodi LibreElec

### ISSUE THREAD

**Issue by mschindl** [ryansch/docker-unifi-rpi#71]
Hello,

is it possible to change port 8080 in the compose file?

Container can't start, because kodi LibreElec already use the port.

Thank you

**Comment by ryansch** [comment]
Sure! You'd need to move away from `host` networking or possibly configure the unifi controller to use a different port (I've never done this).

Alternatively you could try macvlan networking which gives the container its own MAC address and IP address. I have an example with pihole here: https://github.com/ryansch/docker-pihole

**Comment by mschindl** [comment]
It worked with macvlan and it's mostly the easiest way ;)

My new compose file...

# /storage/docker/unifi/docker-compose.yml 
version: '2'
services:
  unifi:
    image: ryansch/unifi-rpi:latest
    container_name: unifi
    restart: always
    # Uncomment the following to set java options
    # environment:
    #   JAVA_OPTS: -Xmx512M
    volumes:
      # Unifi v5.0.7 creates all of these directories (some remain empty)
      - config:/var/lib/unifi
      - log:/usr/lib/unifi/logs
      - log2:/var/log/unifi
      - run:/usr/lib/unifi/run
      - run2:/run/unifi
      - work:/usr/lib/unifi/work
    networks:
      macvlan:
        ipv4_address: 192.168.0.X
volumes:
  config:
    driver: local
  log:                     
    driver: local
  log2:
    driver: local
  run:
    driver: local
  run2:
    driver: local
  work:
    driver: local
networks:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.0.0/24
