### ISSUE TITLE
Docker tag naming convention to differentiate official and beta versions

### ISSUE THREAD

**Issue by rasmuslp** [ryansch/docker-unifi-rpi#72]
Would it be possible to mark `beta` versions as such in the Docker image tag?

With [semantic versioning](https://semver.org/#spec-item-9) - which it looks like the Unifi Controller already follows to some degree - it would become something like `6.1.20-beta` instead of just `6.1.20`. The added bonus being that the stable version would be identifiable as the highest 'pure' version number.

My use case:
I use [whats-up-docker](https://github.com/fmartinou/whats-up-docker) to monitor containers for image updates. With that, I can specify a regular expression that is used to match on the tags (e.g. `^\d+\.\d+\.\d+$`). However, that doesn't work here.

**Comment by ryansch** [comment]
You should be able to monitor for a shorter tag. For the 6.1 series, there hasn't been a stable release yet so there isn't a `6.1` tag.

**Comment by ryansch** [comment]
Hopefully that will make it ignore 'full versions' and then the notifications will work.

I based the tagging strategy off of a lot of the official images I use at work.

**Comment by rasmuslp** [comment]
Unfortunately, that doesn't work, as what's up docker doesn't handle mutable tags. At least not at the moment, but I gather from this https://github.com/fmartinou/whats-up-docker/issues/22 that it's a planned feature.

**Comment by ryansch** [comment]
@rasmuslp Is there any reason you can't use `latest`?

**Comment by rasmuslp** [comment]
I manage my containers with Ansible, where I specify the exact versions of images. I do this to get a history in git, of what has been running where, and so that I can easily revert to a previously known good image, should a problem occur.

Being able to differentiate `official` and `rc` releases would allow me to specify a broad version range like `^\d+\.\d+\.\d+$` - for use in https://github.com/fmartinou/whats-up-docker - that would work for all future versions, assuming the versioning convention doesn't change of course.
