### ISSUE TITLE
Current 'latest' strategy

### ISSUE THREAD

**Issue by markusdd** [ryansch/docker-unifi-rpi#76]
I'm currently noticing a notable lg in pulling the 'latest' tag forward, which I currently rely on.

I assume your consverative setting is there for a good reason, but can you maybe elaborate what is the problem with the latest 6.0.xxx and 6.1.xxx versions?

**Comment by ryansch** [comment]
My `latest` tag tracks the most recent 'stable' version from ubnt. That's currently `6.0.43`. The `6.1` series hasn't yet had a stable release.

**Comment by markusdd** [comment]
Is it? When I pull I get 6.0.36 with latest.

**Comment by apiest** [comment]
![image](https://user-images.githubusercontent.com/12031451/104330896-c3459900-54ee-11eb-8383-e40aa19a4b0e.png)

latest is pushed 2 months ago, 6.0.43 19 hours ago so @markusdd seems correct ;-)

**Comment by ryansch** [comment]
🤦 

Looks like the steps I took to build images from a submitted PR were incorrect. I'll get that fixed.

**Comment by ryansch** [comment]
Fixed in 9d727c5201682effffee1b55cba3892e44ebbeef

Thank you @markusdd and @apiest for reporting and confirming this issue!

**Comment by markusdd** [comment]
Thanks for the quick fix!
