### ISSUE TITLE
Controler Offline nach x Stunden

### ISSUE THREAD

**Issue by AdrianFajt** [ryansch/docker-unifi-rpi#78]
Hallo Zusammen, 
ich habe das Problem, dass wenn ich den Controller als Docker compose container auf meinem Raspberry starte, dass ich nach x Stunden (genauer kann ich es leider nicht eingrenzen) die Web Oberfläche nicht mehr erreiche und in der iOS App der Controller als Offline angezeigt wird. 
Ich nutze den "latest" tag im docker-compose, andere auf dem Raspberry laufende Applikationen wie ioBroker sind normal erreichbar. IoBroker läuft ebenfalls als docker compose container.
Das OS auf dem Raspi ist das aktuellste RaspberryOS es handelt sich um ein Raspberry 3b mit 2GB RAM.
Ich bin über jeden Hinweis dankbar. Wenn noch mehr Infos benötigt werden stelle ich diese gerne zur Verfügung.
Grüße
Adrian

**Comment by ryansch** [comment]
@AdrianFajt You might want to try playing around with the `JAVA_OPTS` environment variable to limit the JVM's memory. Try `JAVA_OPTS: -Xmx512M` to start.

**Comment by AdrianFajt** [comment]
That solved the issue for me. No crashes ever since. Thanks for the quick support.
