### ISSUE TITLE
topology not showing up

### ISSUE THREAD

**Issue by jimbotel** [ryansch/docker-unifi-rpi#79]
Hi all
First of all, thanks for this great project! I recently installed the image on a rpi and all seems to be working fine except for the topology section, that is empty. 
Before that, I had the controller installed on a Windows 10 laptop and this was working properly. 
Any hints?

Thanks!

**Comment by ryansch** [comment]
@jimbotel What version of the controller are you running?

**Comment by jimbotel** [comment]
Hi @ryansch , any update here?  Yesterday I updated to 6.4.54 and I still can't see the topology.
Thanks!
