### ISSUE TITLE
Restart policy for docker

### ISSUE THREAD

**Issue by lucaszanella** [ryansch/docker-unifi-rpi#8]
Instead of doing separate instructions to run and configure startup initiation for each OS, wouldn't it be better to use [docker's restart policy](https://docs.docker.com/engine/admin/start-containers-automatically/#use-a-restart-policy)?

Example

`docker run -dit --restart unless-stopped redis`

Would be the same for all operating systems

**Comment by lucaszanella** [comment]
Also, instead of using docker-compose, isn't it better to just use the restart policy AND -v commands for each of the folders? I think it'd work better :)

**Comment by ryansch** [comment]
I see what you're saying about making the project more accessible to people who aren't running systemd.  I'd like to improve the docs to show how to run the project using only docker-compose and then fill in with the hypriot/systemd stuff after that as a launching point for people who aren't as familiar with docker.

As for getting rid of docker-compose, it's job is to house all of the docker command line args in an easy to read and portable fashion.  I'd also like to run a more modern mongo container at some point and keeping compose will make that easier.
