### ISSUE TITLE
Two Unifi controllers with different versions at the same time ? 

### ISSUE THREAD

**Issue by doremifajb** [ryansch/docker-unifi-rpi#82]
Hello again ! 
My Unifi Controller is 6.0.45, and since I have 4 EOL APs, I didn't update it. Now, I am replacing two of them with U6 lite (so total of six U6 Lites), and the remaining two are not very important. So I thought it might be better to use the current version of the Controller. But I might still want to change config occasionally. Is it possible to install two controllers with different versions, let the newer one running usually, and when I want to configure the old APs, I stop it and turn the old controller on, where the old one contains only the old APs ? (just so that the newer APs wont get messed up)

**Comment by ryansch** [comment]
It's _probably_ fine. Let us all know how it turns out!

**Comment by doremifajb** [comment]
Thank you ! I will try. Should I change the directory names in docker-compose.yml
      - config:/var/lib/unifi
      - log:/usr/lib/unifi/logs
      - log2:/var/log/unifi
      - run:/usr/lib/unifi/run
      - run2:/run/unifi
      - work:/usr/lib/unifi/work
from unifi to, say, unifi-latest for the second unifi controller ?
