### ISSUE TITLE
USG needs reboot each time changes are made in controller

### ISSUE THREAD

**Issue by xcurtis** [ryansch/docker-unifi-rpi#84]
Is this normal behavior? 

Example:
If I go to Settings (Classic) > Routing & Firewall and change anything there,
the USG will go into Provisioning but will stay that way, regardless of how much time has passed.
Rebooting the USG doesn't recover the adoption, it just hangs on Provisioning again.

The only way I can get the USG to come up seemingly-adopted is if I reboot both the Pi (Controller) and the USG at the same time.

I wasn't sure what forum to post this on but I used your container so I figured this is a good place to start.

RPi4B 4GB
Controller FW: 6.4.54
USG FW: 4.4.55.5377096
Inform URL is set up with private IP of the Pi, 
with the Override inform option enabled.

**Comment by ryansch** [comment]
Honestly that's an upstream issue. I'd ask on the UniFi forums or open a support ticket. You might have bad hardware.

**Comment by xcurtis** [comment]
That's what I was afraid of. I'll hop over there and see what I can find out.

Thanks for the timely answer, much appreciated.
