### ISSUE TITLE
Unifi Version 6.5.54

### ISSUE THREAD

**Issue by jdominiczak** [ryansch/docker-unifi-rpi#88]
Due to the Log4J vulnerability, Unifi has released version 6.5.54 which mitigates the issue.  https://community.ui.com/releases/UniFi-Network-Application-6-5-54/d717f241-48bb-4979-8b10-99db36ddabe1

**Comment by ryansch** [comment]
Thanks! I'll update now.

**Comment by ryansch** [comment]
@jdominiczak Just pushed the images and tags.
