### ISSUE TITLE
Why the repository for ubiquiti is added?

### ISSUE THREAD

**Issue by lucaszanella** [ryansch/docker-unifi-rpi#9]
The ubiquiti repository is added, even though its not used, because the .deb is downloaded from the website. So why did you add?

https://github.com/ryansch/docker-unifi-rpi/blob/master/5.6/Dockerfile

**Comment by ryansch** [comment]
That's left over from when I was only using 'stable' releases.  It can be removed now.

**Comment by ryansch** [comment]
@lucaszanella This has been completed.
