### ISSUE TITLE
Unable to setup new network controller

### ISSUE THREAD

**Issue by mmaxbar** [ryansch/docker-unifi-rpi#96]
Trying to set up 7.2.92 from scratch, following your directions from the wiki to the word.
At the end of the setup process after finishing entering the user and password for the local account, timezone etc. , the web interface of the unifi controller switches to https, after that i cannot make any connection to the unifi controller any more.

Commenting out all the port forwarding in the compose file and defining network-mode = "host" solves it, but there seems to be an issue.

PS: i am running Ubuntu Server 22.04 LTS on Pi4 4GB

**Comment by ryansch** [comment]
@mmaxbar I've updated the wiki. Can you let me know if it makes sense to you?

**Comment by mmaxbar** [comment]
I understand that change,  the updated wiki still has one port configured for container networking:

_ports:
      - "3478:3478/udp"
      - "8080:8080"
      - "8443:8443"
      # Replace the above line with the one below if you're using the caddy container.
      # - "8443"
      - "8880:8880"
      - "8843"
      - "6789:6789"_

Whats 8843 for? Should it also be mapped to a port on the network interface?

**Comment by ryansch** [comment]
@mmaxbar Do you still need help?

**Comment by mmaxbar** [comment]
Thanks, everything works fine with network-mode=host, 
Have not tried container networking because I have no use for it...
