### ISSUE TITLE
Clarify docker-compose setup

### ISSUE THREAD

**Issue by philfreo** [ryansch/docker-unifi-rpi#99]
I noticed that you have two different docker-compose examples:

- https://github.com/ryansch/docker-unifi-rpi/blob/main/docker-compose.yml
- https://github.com/ryansch/docker-unifi-rpi/wiki#container-setup

Should the two be the same? Which one is better to use?

**Comment by ryansch** [comment]
I really need to rewrite those docs.

**Comment by philfreo** [comment]
TLDR - I've been running an older version using https://github.com/ryansch/docker-unifi-rpi/blob/main/docker-compose.yml and I just redid my RaspberryPi from scratch to get on the 64bit OS. Will the same file keep working fine?

**Comment by ryansch** [comment]
Probably. I'd encourage you to upgrade to the versionless compose file if you have time.

**Comment by ryansch** [comment]
@philfreo I've updated the wiki page: https://github.com/ryansch/docker-unifi-rpi/wiki

How does that read now?

**Comment by ryansch** [comment]
Ping @morganick

**Comment by philfreo** [comment]
LGTM, thanks
